packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  'react': '19.0.0-rc-f994737d14-20240522'
  'react-dom': '19.0.0-rc-f994737d14-20240522'
  '@types/react': 'npm:types-react@rc'
  '@types/react-dom': 'npm:types-react-dom@rc'
