packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  'react': '19.0.0-rc-02c0e824-20241028'
  'react-dom': '19.0.0-rc-02c0e824-20241028'
  '@types/react': 'npm:types-react@rc'
  '@types/react-dom': 'npm:types-react-dom@rc'
