name: algolia

on:
  push:
    branches:
      - main

jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the content of algolia.json as config
        id: algolia_config
        run: echo "config=$(cat crawlerConfig.json | jq -r tostring)" >> $GITHUB_OUTPUT
      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          API_KEY: ${{ secrets.API_KEY }}
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
